/******************************************************************************
 *
 * Copyright (c) 2019-2026 Fraunhofer IOSB-INA Lemgo,
 * eine rechtlich nicht selbstaendige Einrichtung der Fraunhofer-Gesellschaft
 * zur Foerderung der angewandten Forschung e.V.
 *
 *****************************************************************************/

export const ERROR = {
    AAS_ALREADY_EXISTS: 'Error.AAS_ALREADY_EXISTS',
    AAS_DOES_NOT_EXIST: 'Error.AAS_DOES_NOT_EXIST',
    AASX_PACKAGE_DOES_NOT_EXIST: 'Error.AASX_PACKAGE_DOES_NOT_EXISTs',
    BAD_REQUEST: 'Error.BAD_REQUEST',
    CONCEPT_DESCRIPTION_ALREADY_EXISTS: 'Error.CONCEPT_DESCRIPTION_ALREADY_EXISTS',
    CONCEPT_DESCRIPTION_DOES_NOT_EXIST: 'Error.CONCEPT_DESCRIPTION_DOES_NOT_EXIST',
    DESERIALIZATION_ERROR: 'Error.DESERIALIZATION_ERROR',
    FILE_HAS_NO_ATTACHMENT: 'Error.FILE_HAS_NO_ATTACHMENT',
    INTERNAL_SERVER_ERROR: 'Error.INTERNAL_SERVER_ERROR',
    INVALID_ASSET_ID: 'Error.INVALID_ASSET_ID',
    INVALID_ID_SHORT_PATH: 'Error.INVALID_ID_SHORT_PATH',
    INVALID_OPERATION: 'Error.INVALID_OPERATION',
    INVALID_PACKAGE_ID: 'Error.INVALID_PACKAGE_ID',
    INVALID_VALUE_TYPE: 'Error.INVALID_VALUE_TYPE',
    PROPERTY_EXPECTED: 'Error.PROPERTY_EXPECTED',
    SUBMODEL_ALREADY_EXISTS: 'Error.SUBMODEL_ALREADY_EXISTS',
    SUBMODEL_DOES_NOT_EXIST: 'Error.SUBMODEL_DOES_NOT_EXISTs',
    SUBMODEL_ELEMENT_DOES_NOT_EXIST: 'Error.SUBMODEL_ELEMENT_DOES_NOT_EXIST',
    SUBMODEL_NOT_CONTAINED: 'Error.SUBMODEL_NOT_CONTAINED',
    SUBMODEL_NOT_REFERENCED: 'Error.SUBMODEL_NOT_REFERENCED',
    THUMBNAIL_DOES_NOT_EXIST: 'Error.THUMBNAIL_DOES_NOT_EXIST',
    UNAUTHORIZED_ACCESS: 'Error.UNAUTHORIZED_ACCESS',
    UNAUTHENTICATED_ACCESS: 'Error.UNAUTHENTICATED_ACCESS',
};
