/******************************************************************************
 *
 * Copyright (c) 2019-2025 Fraunhofer IOSB-INA Lemgo,
 * eine rechtlich nicht selbstaendige Einrichtung der Fraunhofer-Gesellschaft
 * zur Foerderung der angewandten Forschung e.V.
 *
 *****************************************************************************/

export const ERROR = {
    AAS_ALREADY_EXISTS: 'AAS_ALREADY_EXISTS',
    AAS_DOES_NOT_EXIST: 'AAS_DOES_NOT_EXISTs',
    AASX_PACKAGE_DOES_NOT_EXIST: 'AASX_PACKAGE_DOES_NOT_EXISTs',
    UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
    INVALID_PACKAGE_ID: 'INVALID_PACKAGE_ID',
    THUMBNAIL_DOES_NOT_EXIST: 'THUMBNAIL_DOES_NOT_EXIST',
    SUBMODEL_DOES_NOT_EXIST: 'SUBMODEL_DOES_NOT_EXISTs',
    SUBMODEL_ALREADY_EXISTS: 'SUBMODEL_ALREADY_EXISTS',
    CONCEPT_DESCRIPTION_DOES_NOT_EXIST: 'CONCEPT_DESCRIPTION_DOES_NOT_EXIST',
    CONCEPT_DESCRIPTION_ALREADY_EXISTS: 'CONCEPT_DESCRIPTION_ALREADY_EXISTS',
    FILE_HAS_NO_ATTACHMENT: 'FILE_HAS_NO_ATTACHMENT',
    DESERIALIZATION_ERROR: 'DESERIALIZATION_ERROR',
    ASSET_ADMINISTRATION_SHELL_ALREADY_EXISTS: 'ASSET_ADMINISTRATION_SHELL_ALREADY_EXISTS',
    ASSET_ADMINISTRATION_SHELL_DOES_NOT_EXIT: 'ASSET_ADMINISTRATION_SHELL_DOES_NOT_EXIT',
    SUBMODEL_NOT_REFERENCED: 'SUBMODEL_NOT_REFERENCED',
    INVALID_OPERATION: 'INVALID_OPERATION',
    INVALID_ID_SHORT_PATH: 'INVALID_ID_SHORT_PATH',
    SUBMODEL_ELEMENT_DOES_NOT_EXIST: 'SUBMODEL_ELEMENT_DOES_NOT_EXIST',
    SUBMODEL_NOT_CONTAINED: 'SUBMODEL_NOT_CONTAINED',
};
