/******************************************************************************
 *
 * Copyright (c) 2019-2025 Fraunhofer IOSB-INA Lemgo,
 * eine rechtlich nicht selbstaendige Einrichtung der Fraunhofer-Gesellschaft
 * zur Foerderung der angewandten Forschung e.V.
 *
 *****************************************************************************/

export const ERROR = {
    AAS_ALREADY_EXISTS: 'Error.AAS_ALREADY_EXISTS',
    AAS_DOES_NOT_EXIST: 'Error.AAS_DOES_NOT_EXISTs',
    AASX_PACKAGE_DOES_NOT_EXIST: 'Error.AASX_PACKAGE_DOES_NOT_EXISTs',
    UNAUTHORIZED_ACCESS: 'Error.UNAUTHORIZED_ACCESS',
    INVALID_PACKAGE_ID: 'Error.INVALID_PACKAGE_ID',
    THUMBNAIL_DOES_NOT_EXIST: 'Error.THUMBNAIL_DOES_NOT_EXIST',
    SUBMODEL_DOES_NOT_EXIST: 'Error.SUBMODEL_DOES_NOT_EXISTs',
    SUBMODEL_ALREADY_EXISTS: 'Error.SUBMODEL_ALREADY_EXISTS',
    CONCEPT_DESCRIPTION_DOES_NOT_EXIST: 'Error.CONCEPT_DESCRIPTION_DOES_NOT_EXIST',
    CONCEPT_DESCRIPTION_ALREADY_EXISTS: 'Error.CONCEPT_DESCRIPTION_ALREADY_EXISTS',
    FILE_HAS_NO_ATTACHMENT: 'Error.FILE_HAS_NO_ATTACHMENT',
    DESERIALIZATION_ERROR: 'Error.DESERIALIZATION_ERROR',
    SUBMODEL_NOT_REFERENCED: 'Error.SUBMODEL_NOT_REFERENCED',
    INVALID_OPERATION: 'Error.INVALID_OPERATION',
    INVALID_ID_SHORT_PATH: 'Error.INVALID_ID_SHORT_PATH',
    SUBMODEL_ELEMENT_DOES_NOT_EXIST: 'Error.SUBMODEL_ELEMENT_DOES_NOT_EXIST',
    SUBMODEL_NOT_CONTAINED: 'Error.SUBMODEL_NOT_CONTAINED',
};
