# Dockerfile to build client app
ARG NGINX_IMAGE=nginx:latest
ARG NODE_IMAGE=node:22.16.0-alpine

FROM $NODE_IMAGE AS build
WORKDIR /usr/src/app
COPY . .
RUN npm ci
RUN npm run aas-portal:build

FROM $NGINX_IMAGE AS aas-portal
#possibility to check host & port availability of other containers via netcat
RUN apt-get update -y && apt-get install -y netcat-openbsd
COPY --from=build /usr/src/app/projects/aas-portal/dist/browser/ /usr/share/nginx/html/
COPY --from=build /usr/src/app/welcome/ /usr/share/nginx/html/assets/welcome/
COPY --from=build /usr/src/app/projects/aas-portal/src/config.js /usr/share/nginx/html/config.js
COPY --from=build /usr/src/app/projects/aas-portal/src/config.js /usr/src/app/wwwroot/config.js.template
COPY --from=build /usr/src/app/projects/aas-portal/nginx.conf /etc/nginx/nginx.conf
COPY docker-entrypoint-aas-portal.sh /docker-entrypoint-aas-portal.sh
RUN chmod +x /docker-entrypoint-aas-portal.sh
EXPOSE 80
ENTRYPOINT ["/docker-entrypoint-aas-portal.sh"]
CMD ["nginx", "-g", "daemon off;"]
