# Creates an aas-server image
ARG NODE_IMAGE=node:24.18.0-alpine

FROM $NODE_IMAGE AS build
ARG GITHUB_RUN_NUMBER=520
ARG GITHUB_REF_NAME=development
WORKDIR /usr/src/app
COPY . .
RUN npm ci
RUN npm run set-version $GITHUB_RUN_NUMBER $GITHUB_REF_NAME
RUN npm run build -w=aas-core -w=aas-package -w=aas-lib -w=aas-server -w=aas-browser

FROM $NODE_IMAGE AS aas-server
RUN apk upgrade --update-cache --available && apk add openssl && rm -rf /var/cache/apk/*
WORKDIR /usr/src/app
COPY --from=build /usr/src/app/projects/aas-server/package.json package.json
RUN npm install --omit=dev
COPY --from=build /usr/src/app/projects/aas-server/src/assets assets/
COPY --from=build /usr/src/app/projects/aas-server/dist/ .
COPY --from=build /usr/src/app/projects/aas-browser/dist/browser wwwroot/
COPY --from=build /usr/src/app/projects/aas-core/dist/ node_modules/aas-core/dist/
COPY --from=build /usr/src/app/projects/aas-core/package.json node_modules/aas-core/package.json
COPY --from=build /usr/src/app/projects/aas-package/dist/ node_modules/aas-package/dist/
COPY --from=build /usr/src/app/projects/aas-package/package.json node_modules/aas-package/package.json
COPY --from=build /usr/src/app/projects/aas-lib/dist/ node_modules/aas-lib/dist/
COPY --from=build /usr/src/app/projects/aas-lib/package.json node_modules/aas-lib/package.json

EXPOSE 50010
CMD ["node", "aas-server.js" ]
