name: Build-and-test-workflow

# This example workflow assumes that the default branch for your repository is `main`. If the default branch has a different name, edit this example and add your repository's default branch.
on:
  push:
  pull_request:
    types:
      - opened

#
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: 24.12.0
      - run: npm ci --unsafe-perm=true --allow-root
      - run: npm run set-version ${{ github.run_number }} ${{ github.ref_name }}
      - run: npm run build
      - run: npm run lint
      - run: npm run test
      - run: npm run coverage
      - name: Archive code coverage results
        uses: actions/upload-artifact@v6
        with:
          name: code-coverage-report
          path: |
            coverage/aas-core.xml
            coverage/aas-package.xml
            coverage/aas-node.xml
            coverage/aas-server.xml
            coverage/aas-lib.xml
            coverage/aas-portal.xml
            coverage/aas-browser.xml
