name: Versioning-workflow
on:
  push:
    branches:
      - main
      - staging
      - development
    

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.SEMANTIC_RELEASE_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.SEMANTIC_RELEASE_MAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.SEMANTIC_RELEASE_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.SEMANTIC_RELEASE_MAIL }}
        run: npx semantic-release
